from sqlalchemy.orm import Session

from app.models.comparison import Comparison
from app.models.user import User
from app.services.comparison_service import get_or_build_comparison
from app.services.playlist_builder import build_playlist_track_ids
from app.services.profile_service import get_or_build_profile
from app.services.spotify_client import add_tracks_to_playlist, create_playlist, get_client
from app.services.spotify_data import ensure_valid_access_token


def generate_playlist(db: Session, user_a: User, user_b: User) -> Comparison:
    comparison = get_or_build_comparison(db, user_a, user_b)
    profile_a = get_or_build_profile(db, user_a)
    profile_b = get_or_build_profile(db, user_b)

    shared_artist_ids = set(profile_a.top_artist_ids) & set(profile_b.top_artist_ids)
    shared_eras = set(profile_a.era_vector) & set(profile_b.era_vector)

    track_ids = build_playlist_track_ids(
        profile_a.top_track_ids,
        profile_b.top_track_ids,
        profile_a.track_meta,
        profile_b.track_meta,
        shared_artist_ids,
        shared_eras,
    )

    name_a = user_a.display_name or "User A"
    name_b = user_b.display_name or "User B"
    match_pct = int(comparison.overall_score)
    playlist_name = f"{name_a} x {name_b} -- {match_pct}% Match"
    description = (
        f"Generated by Spotify Taste Comparator. "
        f"{name_a} and {name_b} are {match_pct}% compatible."
    )

    # The playlist is created under user_a's account, since that's whose token
    # is authorizing this request.
    access_token = ensure_valid_access_token(db, user_a)
    sp = get_client(access_token)
    playlist_id = create_playlist(sp, user_a.spotify_id, playlist_name, description)
    add_tracks_to_playlist(sp, playlist_id, track_ids)

    comparison.playlist_track_ids = track_ids
    comparison.spotify_playlist_id = playlist_id
    db.commit()
    db.refresh(comparison)
    return comparison
